---
title: "RWorksheet_Infiesto#2"
author: "Infiesto"
date: "2024-09-25"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 1. 
```{r}
# 1. Create a vector using : operator
# a. Sequence from -5 to 5. Write the R code and its output.

vectorA <- -5:5
vectorA
```
```{r}
# b. x <- 1:7. What will be the value of x?
x <- 1:7
x
```
2.
```{r}
# 2.* Create a vector using seq() function
#  seq(1, 3, by=0.2) # specify step size
vectorB <- seq(1, 3, by=0.2)
vectorB
```
3.
```{r}
# 3. A factory has a census of its workers. There are 50 workers in total. The following list shows their ages: 34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18.

# a. Access 3rd element, what is the value?
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
          35, 31, 27, 22, 37, 34, 19, 20, 57, 49,
          50, 37, 46, 25, 17, 37, 43, 53, 41, 51,
          35, 24, 33, 41, 53, 40, 18, 44, 38, 41,
          48, 27, 39, 19, 30, 61, 54, 58, 26, 18)
thridelement <- ages[3]
thridelement

# b. Access 2nd and 4th element, what are the values?
secondfourt <- ages[c(2, 4)]
secondfourt

# c. Access all but the 4th and 12th element is not included. Write the R script and its output.
fourthtwelve <- ages[-c(4, 12)]
fourthtwelve
```
4.
```{r}
# 4. *Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the vector, names(x).

x <- c("first" = 3, "second" = 0, "third" = 9)

names(x)

# a. Print the results. Then access x[c("first", "third")].
x1 <- x[c("first", "third")]
x1
```
5.
```{r}
# 5. Create a sequence x from -3:2.
# a. Modify 2nd element and change it to 0;
x <- -3:2
x[2] <- 0
x
```
6.
```{r}
# 6. *The following data shows the diesel fuel purchased by Mr. Cruz.

#a. Create a data frame for month, price per liter (php) and purchase-quantity (liter). Write the R scripts and its output.
Month <- c("Jan", "Feb", "March", "Apr", "May", "June")
PricePerLiter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
PurchaseQuantity <- c(25, 30, 40, 50, 10, 45)

FuelData <- data.frame(Month, PricePerLiter, PurchaseQuantity)

print(FuelData)

# b. What is the average fuel expenditure of Mr. Cruz from Jan to June? Note: Use ‘weighted.mean(liter, purchase)‘.
AverageFuelExpenditure <- weighted.mean(PricePerLiter, PurchaseQuantity)
print(AverageFuelExpenditure)
```
7.
```{r}
# 7. R has actually lots of built-in datasets. For example, the rivers data “gives the lengths (in miles) of 141 “major” rivers in North America, as compiled by the US Geological Survey”.

# a. Type “rivers” in your R console. Create a vector data with 7 elements, containing the number of elements (length) in rivers, their sum (sum), mean (mean), median(median), variance(var), standard deviation(sd), minimum (min) and maximum (max). data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
data(rivers)
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers), sd(rivers), min(rivers), max(rivers))
print(data)
```
8.
```{r}
# 8. The table below gives the 25 most powerful celebrities and their annual pay as ranked by the editions of Forbes magazine and as listed on the Forbes.com website.
# a. Create vectors according to the above table.
PowerRanking <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25)
CelebrityName <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K. Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay Leno", "Celine Dion", "Kobe Bryant")
Pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
Forbes <- data.frame(PowerRanking, CelebrityName, Pay)
print(Forbes)

#b. Modify the power ranking and pay of J.K. Rowling. Change power ranking to 15 and pay to 90. Write the R scripts and its output.
Forbes[Forbes$CelebrityName == "J.K. Rowling", "PowerRanking"] <- 15
Forbes[Forbes$CelebrityName == "J.K. Rowling", "Pay"] <- 90
print(Forbes)

#c. Create an excel file from the table above and save it as csv file(PowerRanking). Import the csv file into the RStudio.
setwd("/cloud/project/ChristianLee/Worksheet#2") 
PowerRanking <- read.csv("PowerRanking.csv")
print(PowerRanking)
print(PowerRanking)

#d. Access the rows 10 to 20 and save it as Ranks.RData.
subset_ranks <- PowerRanking[10:20,]
save(subset_ranks, file = "Ranks.RData")
print(subset_ranks)

```
```{r}
#9. Download the Hotels-Vienna https://tinyurl.com/Hotels-Vienna
#a. Import the excel file into your RStudio.
install.packages("readxl")
library(readxl)
file_path <- "/cloud/project/ChristianLee/Worksheet#2/hotels-vienna.xlsx"  
hotels_data <- read_excel(file_path)
print(hotels_data)

#b. How many dimensions does the dataset have?
dimensions <- dim(hotels_data)
print(dimensions)

#c. Select columns country, neighbourhood, price, stars, accomodation_type, and ratings.
install.packages("dplyr")
library(dplyr)
selected_columns <- hotels_data %>%
  select(country, neighbourhood, price, stars, accommodation_type, rating)
print(selected_columns)

#d. Save the data as **new.RData to your RStudio.
save(selected_columns, file = "new.RData")
file.exists("new.RData")

#e. Display the first six rows and last six rows of the new.RData.
head(selected_columns)
tail(selected_columns)

```
10.
```{r}
#10. Create a list of ten (10) vegetables you ate during your lifetime. If none, just list down.
#a.
vegetables <- c("Carrot", "Broccoli", "Spinach", "Potato", "Tomato", "Cucumber", "Pepper", "Lettuce", "Onion", "Garlic")
vegetables

#b. Add 2 additional vegetables after the last vegetables in the list.
vegetables <- c(vegetables, "Zucchini", "Eggplant")
vegetables

#c. Add 4 additional vegetables after index 5. How many datapoints does your vegetable list have?
vegetables <- append(vegetables, c("Pumpkin", "Kale", "Beetroot", "Radish"), after = 5)
vegetables

#d. Remove the vegetables in index 5, 10, and 15. How many vegetables were left?
vegetables <- vegetables[-c(5, 10, 15)]
vegetables

```


