---
title: "RWorksheet_Infiesto#4a"
author: "Infiesto"
date: "2024-10-22"
output:
  pdf_document: default
  html_document: default
---
1.
```{r}
#1. The table below shows the data about shoe size and height.
#a. Describe the data.
#The table shows information about people’s shoe size, height, and gender (M for male, F for female). It lists these details for different individuals, allowing us to compare shoe sizes and heights between males and females. This data can help us see patterns or differences between the two groups.

#b. Create a subset by males and females with their corresponding shoe size and height. What its result? Show the R scripts.
# Create the data frame
household_data <- data.frame(
  Shoe_Size = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 10.5, 10.5, 8.5, 10.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 10.5, 9.0, 13.0, 11.0, 9.0, 13.0),
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 72.0, 72.0, 74.5, 67.0, 71.0, 71.0, 67.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 72.0, 69.0, 71.0, 69.0, 69.0, 70.0),
  Gender = c('F', 'F', 'F', 'M', 'M', 'F', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'M')
)
md <- subset(household_data, Gender == "M")
fd <- subset(household_data, Gender == "F")
md
fd

#c. Find the mean of shoe size and height of the respondents. Write the R scripts and its result.
mean_shoe_size <- mean(household_data$Shoe_Size)
mean_height <- mean(household_data$Height)
mean_shoe_size
mean_height

#d. Is there a relationship between shoe size and height? Why?
correlation <- cor(household_data$Shoe_Size, household_data$Height)
correlation

```
2.
```{r}
#2. Construct character vector months to a factor with factor() and assign the result to factor_months_vector. Print out factor_months_vector and assert that R prints out the factor levels below the actual values.
# Create a character vector of months
months <- c("March", "April", "January", "November", "January", "September", "October", "September", "November", "August", "January", "November", "November", "February", "May", "August", "July", "December", "August", "August", "September", "November", "February", "April")
factor_months_vector <- factor(months)
print(factor_months_vector)
levels(factor_months_vector)


#3. Then check the summary() of the months_vector and factor_months_vector. | Inter-pret the results of both vectors. Are they both equally useful in this case?
summary(months)
summary(factor_months_vector)
```
4.
```{r}
#4. Create a vector and factor for the table below.
factor_data <- rep(c("East", "West", "North"), c(1, 4, 3))
new_order_data <- factor(factor_data, levels = c("East", "West", "North"))
print(new_order_data)

```
5.
```{r}
#5. Enter the data below in Excel with file name = import_march.csv

#a. Import the excel file into the Environment Pane using read.table() function.
data <- read.table("import_march.csv", header = TRUE, sep = ",",na.strings = "")
print(data)
```
6.
```{r}
#6. Full Search

#Exhaustive search is a methodology for finding an answer by exploring all possible cases. When trying to find a desired number in a set of given numbers, the method of finding the corresponding number by checking all elements in the set one by one can be called an exhaustive search. Implement an exhaustive search function that meets the input/output conditions below. 

#a. Create an R Program that allows the User to randomly select numbers from 1 to 50. Then display the chosen number. If the number is beyond the range of the selected choice, it will have to display a string “The number selected is beyond the range of 1 to 50”. If number 20 is inputted by the User, it will have to display “TRUE”, otherwise display the input number.

a <- function() {
  num <- as.integer(readline(prompt = "Enter a number between 1 and 50: "))

  if (is.na(num)) {
    print("Invalid")
  } else if (num == 20) {
    print("TRUE")
  } else if (num < 1 || num > 50) {
    print("The number selected is beyond the range of 1 to 50")
  } else {
    print(paste(num))
  }
}

a()
```
7.
```{r}
#7. Change

#At ISATU University’s traditional cafeteria, snacks can only be purchased with bills. A long-standing rule at the concession stand is that snacks must be purchased with as few coins as possible. There are three types of bills: 50 pesos, 100 pesos, 200 pesos, 500 pesos, 1000 pesos.

#a. Write a function that prints the minimum number of bills that must be paid, given the price of the snack. Input: Price of snack (a random number divisible by 50) Output: Minimum number of bills needed to purchase a snack.

min_bills <- function(price) {
  bills <- c(1000, 500, 200, 100, 50)
  count <- 0
  
  if (price %% 50 != 0) return("The price must be a multiple of 50.")

  for (bill in bills) {
    count <- count + price %/% bill
    price <- price %% bill
  }
  
  return(paste("Minimum number of bills needed:", count))
}

min_bills(2700)
```
8.
```{r}
#8. The following is each student’s math score for one semester. Based on this, answer the following questions.

#a. Create a dataframe from the above table. Write the R codes and its output.
students <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)
print(students)


#b. Without using the rowMean function, output the average score of students whose average math score over 90 points during the semester. write R code and its output. 
#Example Output: Annie’s average grade this semester is 88.75.

students$Average <- rowMeans(students[2:5])
above90 <- students[students$Average > 90, "Average"]

if (length(above90) > 0) {
  cat(students$Name[students$Average > 90], "’s average grade this semester is", round(above90, 2), "\n")
}


#c. Without using the mean function, output as follows for the tests in which the average score was less than 80 out of 4 tests.
#Example output: The nth test was difficult.

average_scores <- colMeans(students[2:5])

difficult_tests <- which(average_scores < 80)
if (length(difficult_tests) > 0) {
  cat("The", difficult_tests, "tests were difficult.\n")
}



#d. Without using the max function, output as follows for students whose highest score for a semester exceeds 90 points.
#Example Output: Annie’s highest grade this semester is 95.

for (i in 1:nrow(students)) {
  highest_score <- max(students[i, 2:5])
  if (highest_score > 90) {
    cat(students$Name[i], "’s highest grade this semester is", highest_score, "\n")
  }
}
```





