---
title: "RWorksheet_Infiesto#4b"
author: "Infiesto"
date: "2024-10-30"
output:
  pdf_document: default
  html_document: default
---
```{r}
#1. Using the for loop, create an R script that will display a 5x5 matrix as shown in Figure 1. It must contain vectorA = [1,2,3,4,5] and a 5 x 5 zero 
#Hint Use abs() function to get the absolute value

vectorA <- c(1, 2, 3, 4, 5)
matrixA <- matrix(0,5,5)
for (i in 1:5) {
  for (j in 1:5) {
  matrixA[i, j] <- abs(vectorA[i] - vectorA[j])
  }
}
print(matrixA)
```
```{r}
#2. Print the string "*" using for() function. The output should be the same as shown in Figure

for (i in 1:5) {
  line <- ""
  for (j in 1:i) {
    line <- paste(line, "*", sep = " ")
  }
  print(line)
}

```
```{r}
#3. Get an input from the user to print the Fibonacci sequence starting from the 1st input up to 500. Use repeat and break statements. Write the R Scripts and its output.

printFibonacci <- function(start) {
    if (is.na(start) || start < 1) {
        cat("Please enter a valid starting term (a positive integer).\n")
        return()
    }

    first <- 0
    second <- 1
    next_num <- 0
    current_term <- 1

    while (current_term < start) {
        next_num <- first + second
        first <- second
        second <- next_num
        current_term <- current_term + 1
    }

    repeat {
        if (next_num > 500) break
        cat(next_num, ", ")
        
        next_num <- first + second
        first <- second
        second <- next_num
    }
}

start <- as.numeric(readline(prompt = "Enter starting term: "))
printFibonacci(start)

```
```{r}
#4. Import the dataset as shown in Figure 1 you have created previously.

#a. What is the R script for importing an excel or a csv file? Display the first 6 rows of the dataset? Show your codes and its result
library(readr)
data <- read_csv("/cloud/project/ChristianLee/Worksheet#4/Dataset.csv", col_names = TRUE)
head(data)


#b. Create a subset for gender(female and male). How many observations are there in Male? How about in Female? Write the R scripts and its output.

num_females <- sum(data$Gender == "F")
num_males <- sum(data$Gender == "M")
num_females
num_males

#c. Create a graph for the number of males and females for Household Data. Use plot(), chart type = barplot. Make sure to place title, legends, and colors. Write the R scripts and its result.
gender_counts <- table(data$Gender)
if (length(gender_counts) > 0) {
    barplot(gender_counts,
            main = "Number of Males and Females",
            xlab = "Gender",
            ylab = "Count",
            col = c("blue", "pink"),
            legend = names(gender_counts))
} else {
    print("No valid gender data found for plotting.")
}

```
```{r}
expenses <- c(60, 10, 5, 25)
labels <- paste0(round(expenses / sum(expenses) * 100), "%")
colors <- c("lightblue", "orange", "lightgreen", "pink")

pie(expenses, labels = labels, col = colors, main = "Dela Cruz Family Monthly Expenses")
legend("topright", legend = c("Food", "Electricity", "Savings", "Miscellaneous"), fill = colors)

```
```{r}
#6. Use the iris dataset.
#data(iris)

#a. Check for the structure of the dataset using the str() function. Describe what you have seen in the output.

data(iris)
str(iris)

#b. Create an R object that will contain the mean of the sepal.length, sepal.width,petal.length,and petal.width. What is the R script and its result?

mean_values <- colMeans(iris[, 1:4])
mean_values

#c. Create a pie chart for the Species distribution. Add title, legends, and colors. Write the R script and its result.

species_counts <- table(iris$Species)
pie(species_counts, main = "Species Distribution in Iris Dataset", 
    col = c("lightblue", "pink", "lightgreen"), 
    labels = c("Setosa", "Versicolor", "Virginica"))
legend("topright", legend = c("Setosa", "Versicolor", "Virginica"), 
       fill = c("lightblue", "pink", "lightgreen"))


#d. Subset the species into setosa, versicolor, and virginica. Write the R scripts and show the last six (6) rows of each species.

setosa <- subset(iris, Species == "setosa")
versicolor <- subset(iris, Species == "versicolor")
virginica <- subset(iris, Species == "virginica")

tail(setosa, 6)
tail(versicolor, 6)
tail(virginica, 6)

#e. Create a scatterplot of the sepal.length and sepal.width using the different species(setosa,versicolor,virginica). Add a title = “Iris Dataset”, subtitle = “Sepal width and length, labels for the x and y axis, the pch symbol and colors should be based on the species.

iris$Species <- as.factor(iris$Species)

plot(iris$Sepal.Length, iris$Sepal.Width, 
     col = c("red", "green", "blue")[as.numeric(iris$Species)],
     pch = c(16, 17, 18)[as.numeric(iris$Species)], 
     xlab = "Sepal Length", ylab = "Sepal Width",
     main = "Iris Dataset", sub = "Sepal Width and Length")

legend("topright", legend = levels(iris$Species), 
       col = c("red", "green", "blue"), pch = c(16, 17, 18))

#f. Interpret the result.

# The scatterplot shows that Setosa is easy to identify because it has smaller sepals and forms a separate cluster. Versicolor and Virginica, on the other hand, overlap in sepal size, though Virginica tends to have slightly longer sepals. This means that to tell Versicolor and Virginica apart, we might need to look at petal size too.
```
```{r}
#7. Import the alexa-file.xlsx. Check on the variations. Notice that there are extra whitespaces among black variants (Black Dot, Black Plus, Black Show, Black Spot). Also on the white variants (White Dot, White Plus, White Show, White Spot).

library(readxl)
library(knitr)

RObject <- read_excel("alexa-file.xlsx")

head(RObject)

#a. Rename the white and black variants by using gsub() function.

RObject$variation <- gsub("Black Dot", "Black_Dot", RObject$variation)
RObject$variation <- gsub("Black Plus", "Black_Plus", RObject$variation)
RObject$variation <- gsub("Black Show", "Black_Show", RObject$variation)
RObject$variation <- gsub("Black Spot", "Black_Spot", RObject$variation)

RObject$variation <- gsub("White Dot", "White_Dot", RObject$variation)
RObject$variation <- gsub("White Plus", "White_Plus", RObject$variation)
RObject$variation <- gsub("White Show", "White_Show", RObject$variation)
RObject$variation <- gsub("White Spot", "White_Spot", RObject$variation)

head(RObject)

#b. Get the total number of each variations and save it into another object. Save the object as variations.RData. Write the R scripts. What is its result?

library(dplyr)

variations_summary <- RObject %>%
  count(variation)

save(variations_summary, file = "variations.RData")
print(variations_summary)

#c. From the variations.RData, create a barplot(). Complete the details of the chart which include the title, color, labels of each bar.

load("variations.RData")

barplot(variations_summary$n, 
        names.arg = variations_summary$variation, 
        col = "pink", 
        main = "Total Number of Variations", 
        xlab = "Variation", 
        ylab = "Count", 
        las = 2,  
        cex.names = 0.7,  
        cex.axis = 0.8)  

#d. Create a barplot() for the black and white variations. Plot it in 1 frame, side by side. Complete the details of the chart.

black_white_variations <- variations_summary %>%
  filter(grepl("Black|White", variation))

black_variations <- black_white_variations %>% filter(grepl("Black", variation))
white_variations <- black_white_variations %>% filter(grepl("White", variation))

par(mfrow = c(1, 2))

barplot(black_variations$n, 
        names.arg = black_variations$variation, 
        col = c("black", "red", "green", "blue", "cyan"), 
        main = "Black Variants", 
        xlab = "Variation", 
        ylab = "Count", 
        las = 2,  
        cex.names = 0.7,  
        cex.axis = 0.8)

barplot(white_variations$n, 
        names.arg = white_variations$variation, 
        col = c("black", "red", "green", "blue", "cyan"), 
        main = "White Variants", 
        xlab = "Variation", 
        ylab = "Count", 
        las = 2,  
        cex.names = 0.7,  
        cex.axis = 0.8)

par(mfrow = c(1, 1))

```






