---
title: "INFIESTO"
output:
  html_document: default
  pdf_document: default
date: "2024-09-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37,
         34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51,
         35, 24, 33, 41)
length(age)
```
2.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37,
         34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51,
         35, 24, 33, 41)
age_reciprocal <- 1 / age
library("MASS")
fractions(age_reciprocal)
```
3.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37,
         34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51,
         35, 24, 33, 41)
new_age <- c(age, 0, age)
new_age
```
4.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37,
         34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51,
         35, 24, 33, 41)
sort_age <- sort(age)
sort_age
```
5.
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37,
         34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51,
         35, 24, 33, 41)
min_age <- min(age)
min_age
```
```{r}
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37,
         34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 42, 53, 41, 51,
         35, 24, 33, 41)
max_age <- max(age)
max_age
```
6.
```{r}
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)
length(data)
```
7.
```{r}
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5, 2.3, 2.5, 2.3, 2.4, 2.7)
data_data <- data * 2
data_data
```
8.1
```{r}
seq1to100 <- seq(1, 100)
seq1to100
```
8.2
```{r}
seq20to60 <- seq(20, 60)
seq20to60
```
8.3
```{r}
seq20to60 <- seq(20, 60)
mean20to60 <- mean(seq20to60)
mean20to60
```
8.4
```{r}
seq51to91 <- seq(51, 91)
sum51to91 <- sum(seq51to91)
sum51to91
```
8.5
```{r}
int1to1000 <- seq(1, 1000)
int1to1000
```
9
```{r}
filter <- Filter(function(i) { all(i %% c(3, 5, 7) != 0) }, seq(100))
print(filter)
```
10
```{r}
backwards_seq <- seq(100, 1, by = -1)
print(backwards_seq)
```
11
```{r}
multiples <- Filter(function(i) { i %% 3 == 0 || i %% 5 == 0 }, seq(1, 24))
sum_multiples <- sum(multiples)

print(multiples)
print(sum_multiples)
```
12

{0 + x + 5 + }
"This statement is either incomplete or contains an extra operator that will cause an error."

13
```{r}
x <- c(72, 86, 92, 63, 88, 89, 91, 92, 75, 75, 77)
x[2]
x[3]
```
14
```{r}
a <- c(1, 2, NA, 4, NA, 6, 7)
print(a, na.print="999")
```
"na.print="999" replaces NA values with 999 only in the printed output."

15
```{r}
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is",name, "and I am",age ,"years old."))
print(R.version.string)
```














